language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
env:
  - ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/bin/activator
before_install:
  - chmod +x ${ACTIVATOR_BIN}
  - unset SBT_OPTS JVM_OPTS
script:
  - ${ACTIVATOR_BIN} -J-Xss2m ++${TRAVIS_SCALA_VERSION} clean compile